apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/cvdejan/edge-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/cvdejan/edge-service
  newTag: 3350e188889233bd68fc7814e8102c193f66254a

replicas:
- count: 1
  name: edge-service
