apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/cvdejan/catalog-service/k8s?ref=b269da752af75c83abcb0f80f3d457db653a78ba

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: ghcr.io/cvdejan/catalog-service
    newTag: b269da752af75c83abcb0f80f3d457db653a78ba

replicas:
  - name: catalog-service
    count: 1